### PR TITLE
fix: enable virtual headless and fix issues with existing code

### LINKED ISSUE #30: Cannot set virtual value to headless
[https://github.com/apify/camoufox-js/blob/master/src/utils.ts#L376](https://github.com/apify/camoufox-js/blob/master/src/utils.ts#L376)

```js
export interface LaunchOptions {
    /** Whether to run the browser in headless mode. Defaults to `false`.
     * Note: On Linux, passing `headless='virtual'` will use Xvfb.
     */
    headless?: boolean;
```
<br />

```
browserType.launch: headless: expected boolean, got string
    at NewBrowser (./dist/sync_api.js:21:38)
```

### PR DESCRIPTION
**Pull request by msjonker**
Allows headless to be set to "virtual" and fixes issues with existing code to make virtual work

Closes #30

### CODE REVIEW

File: src/sync_api.ts [hunk 1]
```diff
@@ -9,27 +9,28 @@ import { LaunchOptions, launchOptions, syncAttachVD } from './utils.js';
 import { VirtualDisplay } from './virtdisplay.js';
 
 export async function Camoufox(launch_options: LaunchOptions) {
-    return NewBrowser(firefox, false, {}, false, false, launch_options);
+    return NewBrowser(firefox, {}, false, false, launch_options);
 }
 
 export async function NewBrowser(
     playwright: BrowserType<Browser>,
-    headless: boolean | 'virtual' = false,
```
Comment (barjin) [inline src/sync_api.ts:17]: This is matching the original Python project's API

File: src/sync_api.ts [hunk 2]
```diff
@@ -9,27 +9,28 @@ import { LaunchOptions, launchOptions, syncAttachVD } from './utils.js';
...
     persistentContext: boolean = false,
     debug: boolean = false,
     launch_options: LaunchOptions = {}
 ): Promise<Browser | BrowserContext> {
+    launch_options.headless ||= false;
+
     let virtualDisplay: VirtualDisplay | null = null;
 
-    if (headless === 'virtual') {
+    if (launch_options.headless === 'virtual') {
```
Comment (barjin) [inline src/sync_api.ts:26]: launch_options.headless can only be a `boolean`

File: src/utils.ts [hunk 3]
```diff
@@ -373,7 +372,7 @@ export interface LaunchOptions {
     /** Whether to run the browser in headless mode. Defaults to `false`.
      * Note: On Linux, passing `headless='virtual'` will use Xvfb.
      */
-    headless?: boolean;
+    headless?: boolean | 'virtual';
```
Comment (barjin) [inline src/utils.ts:375]: this was matching the [original Python project's API](https://github.com/daijro/camoufox/blob/95cc4489d025471368412b035743bb59855b160e/pythonlib/camoufox/utils.py#L357).

**Review by barjin — CHANGES_REQUESTED** [review]
Thank you for your PR!

Note that the API of Camoufox JS was made after the original Camoufox project, and we would like to follow it as closely as possible. In the original project, `launch_options.headless` is only a [`boolean`](https://github.com/daijro/camoufox/blob/95cc4489d025471368412b035743bb59855b160e/pythonlib/camoufox/utils.py#L357). 

`headless='virtual'` can be used only in the `NewBrowser` parameter, which accepts [`boolean | 'virtual'`](https://github.com/daijro/camoufox/blob/95cc4489d025471368412b035743bb59855b160e/pythonlib/camoufox/sync_api.py#L61). 

If you manage to fix the types and function signatures, I think this is good to merge.
Cheers!
